apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-deployment
  namespace: time
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time
  template:
    metadata:
      labels:
        app: time
    spec:
      containers:
        - name: time
          image: dellabeneta/time:dev
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "128Mi"
